import "../styles/globals.css";
import Head from "next/head";
import Layout from "../components/layout";
import Home from "./home";
function MyApp({ Component, pageProps }) {
  return (
    // <Head>
    //   <title>coding site</title>
    //   <meta name="description" content="Generated by create next app" />
    //   <link rel="icon" href="/coding_logo.svg" />
    // </Head>
    <Layout>
      <Component {...pageProps} />
    </Layout>
  );
}

export default MyApp;
